apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vscode-server
  name: vscode-server
  namespace: homeassistant
spec:
  selector:
    matchLabels:
      app: vscode-server
  replicas: 1
  template:
    metadata:
      labels:
        app: vscode-server
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: homeassistant-pv-config
          persistentVolumeClaim:
            claimName: homeassistant-config-pvc
      containers:
        - image: codercom/code-server:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          imagePullPolicy: Always
          name: code-server
          command:
            [
              '/usr/bin/entrypoint.sh',
              '--bind-addr',
              '0.0.0.0:8080',
              '.',
            ]
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: vscode-password
          volumeMounts:
            - mountPath: /home/homeassistant
              name: homeassistant-pv-config
