{{- range .Values.applications }}
{{- $config := $.Values.config -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name | quote }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .wave }}"
spec:
  destination:
    namespace: {{ .namespace | default .name | quote }}
    server: {{ $config.spec.destination.server | quote }}
  project: {{ .project }}
  {{- if .sources }}
  sources:
    {{- with .sources }}
    {{-  . | toYaml | nindent 4 }}
    {{- end }}
  {{- else }}
  source:
  {{- if .tool }}
    {{- with .tool }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- else }}
    path: {{ .path | default .name | quote }}
  {{- end }}
  {{- if .chart }}
    chart: {{ .chart }}
  {{- end }}
    repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision }}
  {{- if .recurse }}
    directory:
      recurse: true
  {{- end }}
  {{- end }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
{{ end -}}