apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  - path: overlays/argocd-cm-patch.yaml
  - path: overlays/argocd-repo-server-patch.yaml
  - path: overlays/argocd-server-patch.yaml
  - path: overlays/argocd-application-controller-patch.yaml